[profile.default]
src = "src"
out = "out"
script = "scripts"
libs = ["lib"]
remappings = [
    "@allo/v2/=lib/allo-v2/contracts/",
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
