[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@allo/v2/=lib/allo-v2/contracts/",
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
