DROP TABLE IF EXISTS care_pledge.users CASCADE;

-- user table schema --
CREATE TABLE care_pledge.users(
  user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name VARCHAR (30) UNIQUE NOT NULL,
  user_password VARCHAR (60) NOT NULL,
  user_email VARCHAR (60) UNIQUE NOT NULL,
  user_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_updated_at TIMESTAMP NULL
  user_wallet_id VARCHAR(60) NULL,
  -- user_currency_code VARCHAR (3) NULL
);